/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BuffNFT__factory } from "./BuffNFT__factory";
export { LocationNFT__factory } from "./LocationNFT__factory";
